### ISSUE TITLE
Location of relevant values values should be determined by statement line number

### ISSUE THREAD

**Issue by algomaster99** [khaes-kth/PatchExplainer#10]
https://khaes-kth.github.io/PatchExplainer/rq3_commit_analysis/iotdb_e5e4f17f703fa7c8e7623d0a8d3120acb0e89fa6_3.html. At line 94, `modFile`'s value changes, but it is not detected.

**Comment by khesoem** [comment]
Aman says maybe he can put a breakpoint at line 94 too.

**Comment by algomaster99** [comment]
This issue affected two commits:
- https://khaes-kth.github.io/PatchExplainer/rq3_commit_analysis/iotdb_e5e4f17f703fa7c8e7623d0a8d3120acb0e89fa6_3.html 
- https://khaes-kth.github.io/PatchExplainer/rq3_commit_analysis/iotdb_5faa9da049e304bc519a2b96d47cc78d0bdbb9d1_3.html (yellow cell). Please note that I updated the cell value from https://khaes-kth.github.io/PatchExplainer/rq3_commit_analysis/iotdb_5faa9da049e304bc519a2b96d47cc78d0bdbb9d1_0.html

Both are fixed now.

**Comment by khesoem** [comment]
Thanks a lot Aman. As always, you saved us :)
