### ISSUE TITLE
Index out of bounds in the latest version (b917bd88)

### ISSUE THREAD

**Issue by algomaster99** [khaes-kth/PatchExplainer#11]
Hi Khashayar,

I am getting an IndexOutOfBounds exception for https://github.com/JMRI/JMRI/commit/0b53ea83694edd52d5a3c15b375e1fe009293007.

### Command
java -jar target/Explainer-1.0-SNAPSHOT-jar-with-dependencies.jar sdiff --commit 0b53ea83694edd52d5a3c15b375e1fe009293007 --slug JMRI/JMRI --left-report-path /home/aman/assert-achievements/collector-sahab/sahab-reports/sahab-reports/0b53ea83694edd52d5a3c15b375e1fe009293007/left.json --right-report-path /home/aman/assert-achievements/collector-sahab/sahab-reports/sahab-reports/0b53ea83694edd52d5a3c15b375e1fe009293007/right.json --left-src-path /home/aman/testrepos/JMRI/gumtree-left/JsonSignalHeadHttpServiceTest.java --right-src-path /home/aman/testrepos/JMRI/gumtree-right/JsonSignalHeadHttpServiceTest.java --selected-tests "jmri.server.json.signalhead.JsonSignalHeadHttpServiceTest" --test-link https://google.com --output-path jmri_0b53ea83694edd52d5a3c15b375e1fe009293007_3.html

### STDOUT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 35213
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Dec 08, 2022 11:12:40 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Dec 08, 2022 11:12:40 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 108, so returning the closest version found: a no-op implementation
Dec 08, 2022 11:12:40 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Unable to find CDP implementation matching 108.
Dec 08, 2022 11:12:40 AM org.openqa.selenium.chromium.ChromiumDriver lambda$new$3
WARNING: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.0.0` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
Dec 08, 2022 11:12:51 AM se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: Line mappings and vars computed.
Dec 08, 2022 11:12:51 AM se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: For commit 0b53ea83694edd52d5a3c15b375e1fe009293007 line mappings and vars computation took 14227 MILLIS
Dec 08, 2022 11:13:48 AM se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: ProgramStateDiff{firstOriginalUniqueStateSummary=UniqueStateSummary{differencingTest=jmri.server.json.signalhead.JsonSignalHeadHttpServiceTest, firstUniqueStateLine=71, firstUniqueVarValLine=81, firstUniqueStateHash=717541050, firstUniqueVarVal='mapper._jsonFactory._rootCharSymbols._seed=-248074715'}, firstPatchedUniqueStateSummary=UniqueStateSummary{differencingTest=jmri.server.json.signalhead.JsonSignalHeadHttpServiceTest, firstUniqueStateLine=71, firstUniqueVarValLine=81, firstUniqueStateHash=-704210400, firstUniqueVarVal='mapper._jsonFactory._rootCharSymbols._seed=-247986443'}, originalUniqueReturn=UniqueReturnSummary{differencingTest=null, firstUniqueVarValLine=null, firstUniqueReturnLine=null, firstUniqueReturnHash=null, firstUniqueVarVal='null'}, patchedUniqueReturn=UniqueReturnSummary{differencingTest=null, firstUniqueVarValLine=null, firstUniqueReturnLine=null, firstUniqueReturnHash=null, firstUniqueVarVal='null'}}
Dec 08, 2022 11:13:48 AM se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator addStateDiffToExecDiffUI
INFO: For commit 0b53ea83694edd52d5a3c15b375e1fe009293007 diff computation took 56542 MILLIS
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator.addStateDiffToExecDiffUI(StateDiffUIManipulator.java:174)
        at se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator.addStateDiffToExecDiffUI(StateDiffUIManipulator.java:135)
        at se.kth.assertgroup.core.analysis.statediff.ui.StateDiffUIManipulator.addStateDiffToExecDiffUI(StateDiffUIManipulator.java:95)
        at se.kth.assertgroup.core.analysis.statediff.StateDiffCommand.call(StateDiffCommand.java:68)
        at se.kth.assertgroup.core.analysis.statediff.StateDiffCommand.call(StateDiffCommand.java:10)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at se.kth.assertgroup.core.analysis.ExecDiffMain.main(ExecDiffMain.java:17)

### Files

[bug.zip](https://github.com/khaes-kth/PatchExplainer/files/10184439/bug.zip)

**Comment by khesoem** [comment]
Hi @algomaster99 

Pull, build and run again. It should be fixed

**Comment by algomaster99** [comment]
Works now. Thank you!

**Comment by algomaster99** [comment]
@khaes-kth do you want me to also note the time of execution? I saw somewhere in our paper that we also need to note the performance.

**Comment by khesoem** [comment]
Yes, please. Save the timing data
