### ISSUE TITLE
False positive case

### ISSUE THREAD

**Issue by algomaster99** [khaes-kth/PatchExplainer#7]
See the diff [here](https://khaes-kth.github.io/PatchExplainer/rq3_commit_analysis/jhipster-lite_510a9752cccdc1f87dd97a658219759237bdc31e_3.html). It seems that elements inside the collection are same. Commit: https://github.com/jhipster/jhipster-lite/commit/510a9752cccdc1f87dd97a658219759237bdc31e

**Comment by khesoem** [comment]
Fortunately, they are not :-)

![image](https://user-images.githubusercontent.com/54890183/191516225-93f29f3f-7dc3-4361-a365-c9402411dc5c.png)

**Comment by algomaster99** [comment]
@khaes-kth Oops, I did not look at them carefully enough.
